version: '2'

services:
  nats:
    image: bitnami/nats:2
    ports:
      - '4222:4222'
      - '6222:6222'
      - '8222:8222'
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'